repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # pin the same version as in pyproject.toml
    rev: v0.15.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/ComPWA/pyright-pre-commit
    rev: v1.1.407
    hooks:
      - id: pyright
